# -*- coding: utf-8 -*-
"""Model Trainer agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ThPF2tzb3hCegQ4iNJoWk2wvPmh23bWF
"""

!pip install fastapi uvicorn scikit-learn pandas numpy joblib pydantic



import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import joblib


def detect_target_column(df: pd.DataFrame):

    if "target" in df.columns:
        return "target"

    binary_cols = [col for col in df.columns if df[col].nunique() == 2]
    if len(binary_cols) == 1:
        return binary_cols[0]
    elif len(binary_cols) > 1:
        return binary_cols[-1]

    unique_count = df.nunique().sort_values()
    return unique_count.index[0]


class ModelTrainerAgent:
    """Trains any sklearn model on a provided DataFrame."""

    def __init__(self, test_size=0.3, random_state=42, save_model=True):
        self.test_size = test_size
        self.random_state = random_state
        self.save_model = save_model

    def run(self, df: pd.DataFrame, model):
        print(f"📁 Dataset shape: {df.shape}")


        target_column = detect_target_column(df)
        print(f"🎯 Target column detected: {target_column}")

        X = df.drop(columns=[target_column])
        y = df[target_column]


        X = pd.get_dummies(X, drop_first=True)


        X_train, X_test, y_train, y_test = train_test_split(
            X, y,
            test_size=self.test_size,
            random_state=self.random_state
        )


        print("🤖 Training model...")
        model.fit(X_train, y_train)


        y_pred = model.predict(X_test)
        accuracy = accuracy_score(y_test, y_pred)

        model_path = None
        if self.save_model:
            model_name = type(model).__name__.lower()
            model_path = f"trained_model_{model_name}.joblib"
            joblib.dump(model, model_path)
            print(f"💾 Saved: {model_path}")

        print("✅ Training complete!")
        print(f"📊 Accuracy: {accuracy*100:.2f}%")

        return {
            "status": "success",
            "accuracy": round(accuracy, 4),
            "model_name": type(model).__name__,
            "target_column": target_column,
            "model_path": model_path
        }

synthetic_df = synthetic_data_agent()     # agent 1
model = model_creator_agent()             # agent 2

trainer = ModelTrainerAgent()             # agent 3
result = trainer.run(df=synthetic_df, model=model)

print(result)





